-- Generated using RoadToGlory's Converter v1.1 (RoadToGlory#9879)

-- Instances:

local Converted = {
	["_edited"] = Instance.new("ScreenGui");
	["_Frame"] = Instance.new("Frame");
	["_Frame1"] = Instance.new("Frame");
	["_Frame2"] = Instance.new("Frame");
	["_Frame3"] = Instance.new("Frame");
	["_UIPadding"] = Instance.new("UIPadding");
	["_holder"] = Instance.new("Frame");
	["_Frame4"] = Instance.new("Frame");
	["_Frame5"] = Instance.new("Frame");
	["_UIPadding1"] = Instance.new("UIPadding");
	["_Frame6"] = Instance.new("Frame");
	["_Frame7"] = Instance.new("Frame");
	["_Frame8"] = Instance.new("Frame");
	["_UIGradient"] = Instance.new("UIGradient");
	["_UIPadding2"] = Instance.new("UIPadding");
	["_Frame9"] = Instance.new("Frame");
	["_UIListLayout"] = Instance.new("UIListLayout");
	["_UIPadding3"] = Instance.new("UIPadding");
	["_Frame10"] = Instance.new("Frame");
	["_Frame11"] = Instance.new("Frame");
	["_Frame12"] = Instance.new("Frame");
	["_UIGradient1"] = Instance.new("UIGradient");
	["_bar"] = Instance.new("Frame");
	["_UIGradient2"] = Instance.new("UIGradient");
	["_holder1"] = Instance.new("Frame");
	["_UIPadding4"] = Instance.new("UIPadding");
	["_playerinfo"] = Instance.new("Frame");
	["_icon"] = Instance.new("Frame");
	["_Frame13"] = Instance.new("Frame");
	["_Frame14"] = Instance.new("Frame");
	["_ImageLabel"] = Instance.new("ImageLabel");
	["_UIGradient3"] = Instance.new("UIGradient");
	["_health"] = Instance.new("Frame");
	["_Frame15"] = Instance.new("Frame");
	["_Frame16"] = Instance.new("Frame");
	["_UIGradient4"] = Instance.new("UIGradient");
	["_healthbarvalue"] = Instance.new("Frame");
	["_UIGradient5"] = Instance.new("UIGradient");
	["_healthvalue"] = Instance.new("TextLabel");
	["_UIStroke"] = Instance.new("UIStroke");
	["_Frame17"] = Instance.new("Frame");
	["_UIListLayout1"] = Instance.new("UIListLayout");
	["_name"] = Instance.new("TextLabel");
	["_UIStroke1"] = Instance.new("UIStroke");
	["_studs"] = Instance.new("TextLabel");
	["_UIStroke2"] = Instance.new("UIStroke");
	["_armor"] = Instance.new("Frame");
	["_Frame18"] = Instance.new("Frame");
	["_Frame19"] = Instance.new("Frame");
	["_UIGradient6"] = Instance.new("UIGradient");
	["_armorbarvalue"] = Instance.new("Frame");
	["_UIGradient7"] = Instance.new("UIGradient");
	["_armorvalue"] = Instance.new("TextLabel");
	["_UIStroke3"] = Instance.new("UIStroke");
	["_top"] = Instance.new("Frame");
	["_TextLabel"] = Instance.new("TextLabel");
	["_UIPadding5"] = Instance.new("UIPadding");
	["_UIStroke4"] = Instance.new("UIStroke");
	["_top1"] = Instance.new("Frame");
	["_TextLabel1"] = Instance.new("TextLabel");
	["_UIPadding6"] = Instance.new("UIPadding");
	["_UIStroke5"] = Instance.new("UIStroke");
}

-- Properties:

Converted["_edited"].ZIndexBehavior = Enum.ZIndexBehavior.Sibling
Converted["_edited"].Name = "edited"
Converted["_edited"].Parent = gethui()

Converted["_Frame"].AnchorPoint = Vector2.new(0.5, 0)
Converted["_Frame"].BackgroundColor3 = Color3.fromRGB(10.000000353902578, 10.000000353902578, 10.000000353902578)
Converted["_Frame"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Frame"].BorderSizePixel = 0
Converted["_Frame"].Position = UDim2.new(0.5, 0, 1, -250)
Converted["_Frame"].Size = UDim2.new(0, 322, 0, 147)
Converted["_Frame"].Parent = Converted["_edited"]

Converted["_Frame1"].BackgroundColor3 = Color3.fromRGB(96.00000187754631, 120.00000044703484, 190.0000038743019)
Converted["_Frame1"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Frame1"].BorderSizePixel = 0
Converted["_Frame1"].Position = UDim2.new(0, 1, 0, 1)
Converted["_Frame1"].Size = UDim2.new(1, -2, 1, -2)
Converted["_Frame1"].Parent = Converted["_Frame"]

Converted["_Frame2"].BackgroundColor3 = Color3.fromRGB(30.00000011175871, 30.00000011175871, 30.00000011175871)
Converted["_Frame2"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Frame2"].BorderSizePixel = 0
Converted["_Frame2"].Position = UDim2.new(0, 1, 0, 1)
Converted["_Frame2"].Size = UDim2.new(1, -2, 1, -2)
Converted["_Frame2"].Parent = Converted["_Frame1"]

Converted["_Frame3"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Frame3"].BackgroundTransparency = 1
Converted["_Frame3"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Frame3"].BorderSizePixel = 0
Converted["_Frame3"].Position = UDim2.new(0, 1, 0, 2)
Converted["_Frame3"].Size = UDim2.new(1, -2, 1, -4)
Converted["_Frame3"].Parent = Converted["_Frame2"]

Converted["_UIPadding"].PaddingLeft = UDim.new(0, 6)
Converted["_UIPadding"].Parent = Converted["_Frame3"]

Converted["_holder"].BackgroundColor3 = Color3.fromRGB(45.00000111758709, 45.00000111758709, 45.00000111758709)
Converted["_holder"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_holder"].BorderSizePixel = 0
Converted["_holder"].Position = UDim2.new(0, -3, 0, 16)
Converted["_holder"].Size = UDim2.new(1, 0, 1, -18)
Converted["_holder"].Name = "holder"
Converted["_holder"].Parent = Converted["_Frame3"]

Converted["_Frame4"].BackgroundColor3 = Color3.fromRGB(10.000000353902578, 10.000000353902578, 10.000000353902578)
Converted["_Frame4"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Frame4"].BorderSizePixel = 0
Converted["_Frame4"].Position = UDim2.new(0, 1, 0, 1)
Converted["_Frame4"].Size = UDim2.new(1, -2, 1, -2)
Converted["_Frame4"].Parent = Converted["_holder"]

Converted["_Frame5"].BackgroundColor3 = Color3.fromRGB(20.000000707805157, 20.000000707805157, 20.000000707805157)
Converted["_Frame5"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Frame5"].BorderSizePixel = 0
Converted["_Frame5"].Position = UDim2.new(0, 1, 0, 1)
Converted["_Frame5"].Size = UDim2.new(1, -2, 1, -2)
Converted["_Frame5"].Parent = Converted["_Frame4"]

Converted["_UIPadding1"].PaddingLeft = UDim.new(0, 4)
Converted["_UIPadding1"].PaddingTop = UDim.new(0, 4)
Converted["_UIPadding1"].Parent = Converted["_Frame5"]

Converted["_Frame6"].BackgroundColor3 = Color3.fromRGB(10.000000353902578, 10.000000353902578, 10.000000353902578)
Converted["_Frame6"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Frame6"].BorderSizePixel = 0
Converted["_Frame6"].Size = UDim2.new(1, -4, 1, -4)
Converted["_Frame6"].Parent = Converted["_Frame5"]

Converted["_Frame7"].BackgroundColor3 = Color3.fromRGB(45.00000111758709, 45.00000111758709, 45.00000111758709)
Converted["_Frame7"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Frame7"].BorderSizePixel = 0
Converted["_Frame7"].Position = UDim2.new(0, 1, 0, 1)
Converted["_Frame7"].Size = UDim2.new(1, -2, 1, -2)
Converted["_Frame7"].Parent = Converted["_Frame6"]

Converted["_Frame8"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Frame8"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Frame8"].BorderSizePixel = 0
Converted["_Frame8"].Position = UDim2.new(0, 1, 0, 1)
Converted["_Frame8"].Size = UDim2.new(1, -2, 1, -2)
Converted["_Frame8"].Parent = Converted["_Frame7"]

Converted["_UIGradient"].Color = ColorSequence.new{
	ColorSequenceKeypoint.new(0, Color3.fromRGB(29.99998491257429, 29.99998491257429, 29.99998491257429)),
	ColorSequenceKeypoint.new(1, Color3.fromRGB(20.000006407499313, 20.000006407499313, 20.000006407499313))
}
Converted["_UIGradient"].Parent = Converted["_Frame8"]

Converted["_UIPadding2"].PaddingBottom = UDim.new(0, 3)
Converted["_UIPadding2"].PaddingLeft = UDim.new(0, 4)
Converted["_UIPadding2"].PaddingRight = UDim.new(0, 3)
Converted["_UIPadding2"].PaddingTop = UDim.new(0, 4)
Converted["_UIPadding2"].Parent = Converted["_Frame8"]

Converted["_Frame9"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Frame9"].BackgroundTransparency = 1
Converted["_Frame9"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Frame9"].BorderSizePixel = 0
Converted["_Frame9"].Size = UDim2.new(1, 0, 1, 3)
Converted["_Frame9"].Parent = Converted["_Frame8"]

Converted["_UIListLayout"].Padding = UDim.new(0, 4)
Converted["_UIListLayout"].SortOrder = Enum.SortOrder.LayoutOrder
Converted["_UIListLayout"].Parent = Converted["_Frame9"]

Converted["_UIPadding3"].PaddingBottom = UDim.new(0, 4)
Converted["_UIPadding3"].Parent = Converted["_Frame9"]

Converted["_Frame10"].BackgroundColor3 = Color3.fromRGB(45.00000111758709, 45.00000111758709, 45.00000111758709)
Converted["_Frame10"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Frame10"].BorderSizePixel = 0
Converted["_Frame10"].Size = UDim2.new(1, -1, 1, 0)
Converted["_Frame10"].Parent = Converted["_Frame9"]

Converted["_Frame11"].BackgroundColor3 = Color3.fromRGB(10.000000353902578, 10.000000353902578, 10.000000353902578)
Converted["_Frame11"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Frame11"].BorderSizePixel = 0
Converted["_Frame11"].Position = UDim2.new(0, 1, 0, 1)
Converted["_Frame11"].Size = UDim2.new(1, -2, 1, -2)
Converted["_Frame11"].Parent = Converted["_Frame10"]

Converted["_Frame12"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Frame12"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Frame12"].BorderSizePixel = 0
Converted["_Frame12"].Position = UDim2.new(0, 1, 0, 1)
Converted["_Frame12"].Size = UDim2.new(1, -2, 1, -2)
Converted["_Frame12"].Parent = Converted["_Frame11"]

Converted["_UIGradient1"].Color = ColorSequence.new{
	ColorSequenceKeypoint.new(0, Color3.fromRGB(29.99998491257429, 29.99998491257429, 29.99998491257429)),
	ColorSequenceKeypoint.new(1, Color3.fromRGB(20.000006407499313, 20.000006407499313, 20.000006407499313))
}
Converted["_UIGradient1"].Parent = Converted["_Frame12"]

Converted["_bar"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_bar"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_bar"].BorderSizePixel = 0
Converted["_bar"].Size = UDim2.new(1, 0, 0, 2)
Converted["_bar"].Name = "bar"
Converted["_bar"].Parent = Converted["_Frame12"]

Converted["_UIGradient2"].Color = ColorSequence.new{
	ColorSequenceKeypoint.new(0, Color3.fromRGB(96.00010827183723, 119.99993965029716, 189.9999886751175)),
	ColorSequenceKeypoint.new(1, Color3.fromRGB(100.00003203749657, 112.99993246793747, 168.99997472763062))
}
Converted["_UIGradient2"].Parent = Converted["_bar"]

Converted["_holder1"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_holder1"].BackgroundTransparency = 1
Converted["_holder1"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_holder1"].BorderSizePixel = 0
Converted["_holder1"].Position = UDim2.new(0, 1, 0, 22)
Converted["_holder1"].Size = UDim2.new(1, -2, 1, -24)
Converted["_holder1"].Name = "holder"
Converted["_holder1"].Parent = Converted["_Frame12"]

Converted["_UIPadding4"].PaddingBottom = UDim.new(0, 2)
Converted["_UIPadding4"].PaddingLeft = UDim.new(0, 3)
Converted["_UIPadding4"].PaddingRight = UDim.new(0, 3)
Converted["_UIPadding4"].PaddingTop = UDim.new(0, -1)
Converted["_UIPadding4"].Parent = Converted["_holder1"]

Converted["_playerinfo"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_playerinfo"].BackgroundTransparency = 1
Converted["_playerinfo"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_playerinfo"].BorderSizePixel = 0
Converted["_playerinfo"].Size = UDim2.new(1, 0, 1, 0)
Converted["_playerinfo"].Name = "playerinfo"
Converted["_playerinfo"].Parent = Converted["_holder1"]

Converted["_icon"].BackgroundColor3 = Color3.fromRGB(10.000000353902578, 10.000000353902578, 10.000000353902578)
Converted["_icon"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_icon"].BorderSizePixel = 0
Converted["_icon"].Size = UDim2.new(0, 68, 1, 0)
Converted["_icon"].Name = "icon"
Converted["_icon"].Parent = Converted["_playerinfo"]

Converted["_Frame13"].BackgroundColor3 = Color3.fromRGB(45.00000111758709, 45.00000111758709, 45.00000111758709)
Converted["_Frame13"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Frame13"].BorderSizePixel = 0
Converted["_Frame13"].Position = UDim2.new(0, 1, 0, 1)
Converted["_Frame13"].Size = UDim2.new(1, -2, 1, -2)
Converted["_Frame13"].Parent = Converted["_icon"]

Converted["_Frame14"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Frame14"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Frame14"].BorderSizePixel = 0
Converted["_Frame14"].Position = UDim2.new(0, 1, 0, 1)
Converted["_Frame14"].Size = UDim2.new(1, -2, 1, -2)
Converted["_Frame14"].Parent = Converted["_Frame13"]

Converted["_ImageLabel"].Image = "http://www.roblox.com/asset/?id=119472238324544"
Converted["_ImageLabel"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_ImageLabel"].BackgroundTransparency = 1
Converted["_ImageLabel"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_ImageLabel"].BorderSizePixel = 0
Converted["_ImageLabel"].Size = UDim2.new(1, 0, 1, 0)
Converted["_ImageLabel"].Parent = Converted["_Frame14"]

Converted["_UIGradient3"].Color = ColorSequence.new{
	ColorSequenceKeypoint.new(0, Color3.fromRGB(29.99998491257429, 29.99998491257429, 29.99998491257429)),
	ColorSequenceKeypoint.new(1, Color3.fromRGB(20.000006407499313, 20.000006407499313, 20.000006407499313))
}
Converted["_UIGradient3"].Parent = Converted["_Frame14"]

Converted["_health"].AnchorPoint = Vector2.new(0, 1)
Converted["_health"].BackgroundColor3 = Color3.fromRGB(10.000000353902578, 10.000000353902578, 10.000000353902578)
Converted["_health"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_health"].BorderSizePixel = 0
Converted["_health"].Position = UDim2.new(0, 72, 1, 0)
Converted["_health"].Size = UDim2.new(1, -72, 0, 14)
Converted["_health"].Name = "health"
Converted["_health"].Parent = Converted["_playerinfo"]

Converted["_Frame15"].BackgroundColor3 = Color3.fromRGB(45.00000111758709, 45.00000111758709, 45.00000111758709)
Converted["_Frame15"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Frame15"].BorderSizePixel = 0
Converted["_Frame15"].Position = UDim2.new(0, 1, 0, 1)
Converted["_Frame15"].Size = UDim2.new(1, -2, 1, -2)
Converted["_Frame15"].Parent = Converted["_health"]

Converted["_Frame16"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Frame16"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Frame16"].BorderSizePixel = 0
Converted["_Frame16"].Position = UDim2.new(0, 1, 0, 1)
Converted["_Frame16"].Size = UDim2.new(1, -2, 1, -2)
Converted["_Frame16"].Parent = Converted["_Frame15"]

Converted["_UIGradient4"].Color = ColorSequence.new{
	ColorSequenceKeypoint.new(0, Color3.fromRGB(29.99998491257429, 29.99998491257429, 29.99998491257429)),
	ColorSequenceKeypoint.new(1, Color3.fromRGB(20.000006407499313, 20.000006407499313, 20.000006407499313))
}
Converted["_UIGradient4"].Parent = Converted["_Frame16"]

Converted["_healthbarvalue"].BackgroundColor3 = Color3.fromRGB(45.00000111758709, 195.0000035762787, 45.00000111758709)
Converted["_healthbarvalue"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_healthbarvalue"].BorderSizePixel = 0
Converted["_healthbarvalue"].Size = UDim2.new(1, 0, 1, 0)
Converted["_healthbarvalue"].Name = "healthbarvalue"
Converted["_healthbarvalue"].Parent = Converted["_Frame16"]

Converted["_UIGradient5"].Color = ColorSequence.new{
	ColorSequenceKeypoint.new(0, Color3.fromRGB(255, 255, 255)),
	ColorSequenceKeypoint.new(1, Color3.fromRGB(124.99997735023499, 124.99997735023499, 124.99997735023499))
}
Converted["_UIGradient5"].Parent = Converted["_healthbarvalue"]

Converted["_healthvalue"].Font = Enum.Font.SourceSans
Converted["_healthvalue"].Text = "100/100"
Converted["_healthvalue"].TextColor3 = Color3.fromRGB(180.00000447034836, 180.00000447034836, 180.00000447034836)
Converted["_healthvalue"].TextSize = 12
Converted["_healthvalue"].AnchorPoint = Vector2.new(0.5, 0.5)
Converted["_healthvalue"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_healthvalue"].BackgroundTransparency = 1
Converted["_healthvalue"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_healthvalue"].BorderSizePixel = 0
Converted["_healthvalue"].Position = UDim2.new(0.5, 0, 0.5, 0)
Converted["_healthvalue"].Size = UDim2.new(1, 0, 1, 0)
Converted["_healthvalue"].Name = "healthvalue"
Converted["_healthvalue"].Parent = Converted["_Frame16"]

Converted["_UIStroke"].LineJoinMode = Enum.LineJoinMode.Miter
Converted["_UIStroke"].Parent = Converted["_healthvalue"]

Converted["_Frame17"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Frame17"].BackgroundTransparency = 1
Converted["_Frame17"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Frame17"].BorderSizePixel = 0
Converted["_Frame17"].Position = UDim2.new(0.270072997, 0, 0.0294117648, 0)
Converted["_Frame17"].Size = UDim2.new(0, 198, 0, 31)
Converted["_Frame17"].Parent = Converted["_playerinfo"]

Converted["_UIListLayout1"].Padding = UDim.new(0, 2)
Converted["_UIListLayout1"].SortOrder = Enum.SortOrder.LayoutOrder
Converted["_UIListLayout1"].Parent = Converted["_Frame17"]

Converted["_name"].Font = Enum.Font.SourceSans
Converted["_name"].Text = "exp (@example)"
Converted["_name"].TextColor3 = Color3.fromRGB(180.00000447034836, 180.00000447034836, 180.00000447034836)
Converted["_name"].TextSize = 12
Converted["_name"].TextXAlignment = Enum.TextXAlignment.Left
Converted["_name"].TextYAlignment = Enum.TextYAlignment.Top
Converted["_name"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_name"].BackgroundTransparency = 1
Converted["_name"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_name"].BorderSizePixel = 0
Converted["_name"].Size = UDim2.new(0.391515255, 0, 0.419354796, 0)
Converted["_name"].Name = "name"
Converted["_name"].Parent = Converted["_Frame17"]

Converted["_UIStroke1"].LineJoinMode = Enum.LineJoinMode.Miter
Converted["_UIStroke1"].Parent = Converted["_name"]

Converted["_studs"].Font = Enum.Font.SourceSans
Converted["_studs"].Text = "123 studs"
Converted["_studs"].TextColor3 = Color3.fromRGB(180.00000447034836, 180.00000447034836, 180.00000447034836)
Converted["_studs"].TextSize = 12
Converted["_studs"].TextXAlignment = Enum.TextXAlignment.Left
Converted["_studs"].TextYAlignment = Enum.TextYAlignment.Top
Converted["_studs"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_studs"].BackgroundTransparency = 1
Converted["_studs"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_studs"].BorderSizePixel = 0
Converted["_studs"].Size = UDim2.new(0.391515255, 0, 0.419354796, 0)
Converted["_studs"].Name = "studs"
Converted["_studs"].Parent = Converted["_Frame17"]

Converted["_UIStroke2"].LineJoinMode = Enum.LineJoinMode.Miter
Converted["_UIStroke2"].Parent = Converted["_studs"]

Converted["_armor"].AnchorPoint = Vector2.new(0, 1)
Converted["_armor"].BackgroundColor3 = Color3.fromRGB(10.000000353902578, 10.000000353902578, 10.000000353902578)
Converted["_armor"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_armor"].BorderSizePixel = 0
Converted["_armor"].Position = UDim2.new(0, 72, 0.79411763, 0)
Converted["_armor"].Size = UDim2.new(1, -72, 0, 14)
Converted["_armor"].Name = "armor"
Converted["_armor"].Parent = Converted["_playerinfo"]

Converted["_Frame18"].BackgroundColor3 = Color3.fromRGB(45.00000111758709, 45.00000111758709, 45.00000111758709)
Converted["_Frame18"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Frame18"].BorderSizePixel = 0
Converted["_Frame18"].Position = UDim2.new(0, 1, 0, 1)
Converted["_Frame18"].Size = UDim2.new(1, -2, 1, -2)
Converted["_Frame18"].Parent = Converted["_armor"]

Converted["_Frame19"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Frame19"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Frame19"].BorderSizePixel = 0
Converted["_Frame19"].Position = UDim2.new(0, 1, 0, 1)
Converted["_Frame19"].Size = UDim2.new(1, -2, 1, -2)
Converted["_Frame19"].Parent = Converted["_Frame18"]

Converted["_UIGradient6"].Color = ColorSequence.new{
	ColorSequenceKeypoint.new(0, Color3.fromRGB(29.99998491257429, 29.99998491257429, 29.99998491257429)),
	ColorSequenceKeypoint.new(1, Color3.fromRGB(20.000006407499313, 20.000006407499313, 20.000006407499313))
}
Converted["_UIGradient6"].Parent = Converted["_Frame19"]

Converted["_armorbarvalue"].BackgroundColor3 = Color3.fromRGB(45.00000111758709, 45.00000111758709, 195.0000187754631)
Converted["_armorbarvalue"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_armorbarvalue"].BorderSizePixel = 0
Converted["_armorbarvalue"].Size = UDim2.new(1, 0, 1, 0)
Converted["_armorbarvalue"].Name = "armorbarvalue"
Converted["_armorbarvalue"].Parent = Converted["_Frame19"]

Converted["_UIGradient7"].Color = ColorSequence.new{
	ColorSequenceKeypoint.new(0, Color3.fromRGB(255, 255, 255)),
	ColorSequenceKeypoint.new(1, Color3.fromRGB(124.99997735023499, 124.99997735023499, 124.99997735023499))
}
Converted["_UIGradient7"].Parent = Converted["_armorbarvalue"]

Converted["_armorvalue"].Font = Enum.Font.SourceSans
Converted["_armorvalue"].Text = "100/100"
Converted["_armorvalue"].TextColor3 = Color3.fromRGB(180.00000447034836, 180.00000447034836, 180.00000447034836)
Converted["_armorvalue"].TextSize = 12
Converted["_armorvalue"].AnchorPoint = Vector2.new(0.5, 0.5)
Converted["_armorvalue"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_armorvalue"].BackgroundTransparency = 1
Converted["_armorvalue"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_armorvalue"].BorderSizePixel = 0
Converted["_armorvalue"].Position = UDim2.new(0.5, 0, 0.5, 0)
Converted["_armorvalue"].Size = UDim2.new(1, 0, 1, 0)
Converted["_armorvalue"].Name = "armorvalue"
Converted["_armorvalue"].Parent = Converted["_Frame19"]

Converted["_UIStroke3"].LineJoinMode = Enum.LineJoinMode.Miter
Converted["_UIStroke3"].Parent = Converted["_armorvalue"]

Converted["_top"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_top"].BackgroundTransparency = 1
Converted["_top"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_top"].BorderSizePixel = 0
Converted["_top"].Position = UDim2.new(0, 0, 0, 2)
Converted["_top"].Size = UDim2.new(1, 0, 0, 20)
Converted["_top"].Name = "top"
Converted["_top"].Parent = Converted["_Frame12"]

Converted["_TextLabel"].Font = Enum.Font.SourceSans
Converted["_TextLabel"].Text = "Info"
Converted["_TextLabel"].TextColor3 = Color3.fromRGB(136.00000709295273, 136.00000709295273, 136.00000709295273)
Converted["_TextLabel"].TextSize = 12
Converted["_TextLabel"].TextXAlignment = Enum.TextXAlignment.Left
Converted["_TextLabel"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_TextLabel"].BackgroundTransparency = 1
Converted["_TextLabel"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_TextLabel"].BorderSizePixel = 0
Converted["_TextLabel"].Size = UDim2.new(1, 0, 1, 0)
Converted["_TextLabel"].Parent = Converted["_top"]

Converted["_UIPadding5"].PaddingLeft = UDim.new(0, 5)
Converted["_UIPadding5"].Parent = Converted["_TextLabel"]

Converted["_UIStroke4"].LineJoinMode = Enum.LineJoinMode.Miter
Converted["_UIStroke4"].Parent = Converted["_TextLabel"]

Converted["_top1"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_top1"].BackgroundTransparency = 1
Converted["_top1"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_top1"].BorderSizePixel = 0
Converted["_top1"].Size = UDim2.new(1, -4, 0, 20)
Converted["_top1"].Name = "top"
Converted["_top1"].Parent = Converted["_Frame3"]

Converted["_TextLabel1"].Font = Enum.Font.SourceSans
Converted["_TextLabel1"].Text = "Indicator"
Converted["_TextLabel1"].TextColor3 = Color3.fromRGB(180.00000447034836, 180.00000447034836, 180.00000447034836)
Converted["_TextLabel1"].TextSize = 12
Converted["_TextLabel1"].TextXAlignment = Enum.TextXAlignment.Left
Converted["_TextLabel1"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_TextLabel1"].BackgroundTransparency = 1
Converted["_TextLabel1"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_TextLabel1"].BorderSizePixel = 0
Converted["_TextLabel1"].Size = UDim2.new(0.5, 0, 1, 0)
Converted["_TextLabel1"].Parent = Converted["_top1"]

Converted["_UIPadding6"].PaddingBottom = UDim.new(0, 4)
Converted["_UIPadding6"].PaddingLeft = UDim.new(0, -2)
Converted["_UIPadding6"].PaddingTop = UDim.new(0, -4)
Converted["_UIPadding6"].Parent = Converted["_TextLabel1"]

Converted["_UIStroke5"].LineJoinMode = Enum.LineJoinMode.Miter
Converted["_UIStroke5"].Parent = Converted["_TextLabel1"]

local juju = juju -- i hate type errors in vscode sorry
local create_connection = juju.create_connection
local run_service = cloneref(game:GetService("RunService"))
local players = cloneref(game:GetService("Players"))
local tween_service = game:GetService("TweenService")
local get_target = juju.get_ragebot_target
local create_notification = juju.create_notification

local dropdown = juju["create_element"]({
    ["name"] = "mode"
}, {
    ["dropdown"] = {
        ["default"] = {"ragebot"},
        ["options"] = {"ragebot", "legitbot"},
        ["requires_one"] = true,
        ["multi"] = false,
		["flag"] = "mode_dropdown_targetui"
    }
})

juju["create_connection"](dropdown["on_dropdown_change"], function(val)
    if val[1] == "ragebot" then
		get_target = juju.get_ragebot_target
	else
		get_target = juju.get_legitbot_target
	end
end)

local function update_target_gui()
    local target = get_target()

    if target and target.Character and target.Character:FindFirstChild("Humanoid") then
        local humanoid = target.Character.Humanoid
        local health_ratio = math.clamp(humanoid.Health / humanoid.MaxHealth, 0, 1)
        local lPlayerCharacter = players.LocalPlayer.Character
        local distance = lPlayerCharacter and lPlayerCharacter:FindFirstChild("HumanoidRootPart") and target.Character:FindFirstChild("HumanoidRootPart") and target.Character.HumanoidRootPart.Position - lPlayerCharacter.HumanoidRootPart.Position or Vector3.new(0,0,0)
        local distanceM = distance.Magnitude
        local bodyEffects = target.Character:FindFirstChild("BodyEffects")
        local armorV = bodyEffects and bodyEffects:FindFirstChild("Armor") or nil
        local armor_ratio = armorV and math.clamp(armorV.Value / 130, 0, 1) or 0

        if target.Name ~= target.DisplayName then
            local full = target.DisplayName .. " (@" .. target.Name .. ")"
            if string.len(full) > 30 then
                Converted["_name"].Text = string.sub(full, 1, 27) .. "..."
            else
                Converted["_name"].Text = full
            end
        else
            if string.len(target.Name) > 30 then
                Converted["_name"].Text = string.sub(target.Name, 1, 27) .. "..."
            else
                Converted["_name"].Text = target.Name
            end
        end

        Converted["_studs"].Text = math.floor(distanceM) .. " studs"

		Converted["_healthvalue"].Text = math.floor(humanoid.Health) .. "/" .. math.floor(humanoid.MaxHealth)

        tween_service:Create(Converted["_healthbarvalue"], TweenInfo.new(0.3, Enum.EasingStyle.Quad), {
            Size = UDim2.new(health_ratio, 0, 1, 0)
        }):Play()

        Converted["_armorvalue"].Text = math.floor(armorV.Value) .. "/130"

        tween_service:Create(Converted["_armorbarvalue"], TweenInfo.new(0.3, Enum.EasingStyle.Quad), {
            Size = UDim2.new(armor_ratio, 0, 1, 0)
        }):Play()

		Converted["_ImageLabel"].Image = string.format("rbxthumb://type=AvatarHeadShot&id=%d&w=420&h=420", target.UserId)
        if not Converted["_edited"].Enabled then
            Converted["_edited"].Enabled = true
        end
    else
        if Converted["_edited"].Enabled then
			Converted["_edited"].Enabled = false
		end
    end
end

create_connection(run_service.Heartbeat, function()
    update_target_gui()
end)

for i = 1, 30 do
    print("shaq is so cool and hot")
    create_notification("shaq is so cool and hot mmmm meowww", 1, 2)
end

juju.on_unload(function()
    Converted["_edited"]:Destroy()
    for i = 1, 30 do
        print("shaq is so cool and hot")
        create_notification("shaq is so cool and hot mmmm meowww", 1, 2)
    end
end)
